import '@/styles/globals.scss'
import Layout from '@/components/layout/layout';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  return (
    <Layout>
        <Head>
        <title>Test project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
      <Component {...pageProps} />
    </Layout>
  )
}
